#!/usr/bin/python3
# SPDX-FileCopyrightText: 2022 Aso Hidetoshi asouhide2002@gmaiil.com
# SPDX-License-Identifier: BSD-3-Clause

import socket
import sys

host = 'www.it-chiba.ac.jp'
if len(sys.argv) > 1:
    host = sys.argv[1]

port = 80

sock = socket.socket(socket.AF_INET,socket.SOCK_STREAM)

try:
    sock.connect((host,port))
except:
    sys.exit(1)

req =   b'HEAD / HTTP/1.1\r\n'
req +=  b'HOST: ' + host.encode() + b'\r\n'
req +=  b'Connection: close\r\n\r\n'

req_len = len(req)

if req_len != sock.send(req):
    sys.exit(1)

recv = ''
chunk = sock.recv(1024)
while chunk != b'':
    recv += chunk.decode('utf-8','ignore')
    chunk = sock.recv(1024)

for line in recv.splitlines():
    if('Date' in line):
        print(line[6:])
        sys.exit(0)

sys.exit(1)