#!/usr/bin/python3
# SPDX-FileCopyrightText: 2022 Aso Hidetoshi asouhide2002@gmail.com
# SPDX-License-Identifier: BSD-3-Clause

import sys

ans = 0.0
for line in sys.stdin:
    try:
        ans+=float(line)
    except:
        sys.exit(1)

print(ans)
sys.exit(0)